# SPDX-FileCopyrightText: 2016 The Glucometer Protocols Authors
#
# SPDX-License-Identifier: MIT

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=netlify/glucometer-protocols/deploy-preview"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
  - name: Automatic merge from Flameeyes
    conditions:
      - "author=Flameeyes"
      - "status-success=netlify/glucometer-protocols/deploy-preview"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
