pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=netlify/glucometer-protocols/deploy-preview"
      - "status-success=Travis CI - Pull Request"
    actions:
      merge:
        method: rebase
  - name: Automatic merge from Flameeyes
    conditions:
      - "author=Flameeyes"
      - "status-success=netlify/glucometer-protocols/deploy-preview"
      - "status-success=Travis CI - Pull Request"
    actions:
      merge:
        method: rebase
