# SPDX-FileCopyrightText: 2016 The Glucometer Protocols Authors
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
    - id: reuse
