# SPDX-FileCopyrightText: 2016 The Glucometer Protocols Authors
#
# SPDX-License-Identifier: MIT

dist: xenial

language: python

matrix:
  include:
    - python: 3.7

install:
  - pip install -r requirements.txt

script:
  - pre-commit install
  - pre-commit run --all-files
